### ISSUE TITLE
Szkielet kodu

### ISSUE THREAD

**Issue by nels3** [kamilsajdak96/Zaawansowane-metody-inzynierii-oprogramowania#24]
Wykonywalny kod realizujący jeden z wybranych przypadków użycia – bezkonieczności działających połączeń bazodanowych (dane mogą być ustawione nasztywno) i z placeholderowymi elementami. Prezentacja wykonywalnego kodu jakoprzykładu.

**Comment by SzymiJimi** [comment]
Wykonane.
